"""add purchase_currency to invoices

Revision ID: aa5de6a76355
Revises: 3464ea5ba311
Create Date: 2025-12-04 01:27:10.839458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5de6a76355'
down_revision = '3464ea5ba311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        # SQLite requires a server_default to add a NOT NULL column
        batch_op.add_column(
            sa.Column(
                'purchase_currency',
                sa.String(length=3),
                nullable=False,
                server_default='DKK'
            )
        )
        batch_op.create_index(batch_op.f('ix_invoices_purchase_currency'), ['purchase_currency'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_purchase_currency'))
        batch_op.drop_column('purchase_currency')

    # ### end Alembic commands ###
