"""Add issuing_company_id to invoices and account_holder payment_note to company_settings

Revision ID: c786443b2218
Revises: aa5de6a76355
Create Date: 2025-12-04 02:12:34.755537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c786443b2218'
down_revision = 'aa5de6a76355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_holder', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('payment_note', sa.String(length=200), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issuing_company_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoices_issuing_company_id'), ['issuing_company_id'], unique=False)
        batch_op.create_foreign_key('fk_invoices_issuing_company_id', 'company_settings', ['issuing_company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoices_issuing_company_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_issuing_company_id'))
        batch_op.drop_column('issuing_company_id')

    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_column('payment_note')
        batch_op.drop_column('account_holder')

    # ### end Alembic commands ###
